apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-ci-server
  labels:
    app: sample-ci-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-ci-server
  template:
    metadata:
      labels:
        app: sample-ci-server
        workload: deployment
    spec:
      containers:
        - name: sample-ci-server
          image: 160631388793.dkr.ecr.ap-southeast-2.amazonaws.com/sample-server:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000