apiVersion: v1
kind: Service
metadata:
  name: sample-ci-service
  labels:
    app: sample-ci-server
spec:
  type: LoadBalancer
  selector:
    app: sample-ci-server
    workload: deployment
  ports:
    - protocol: TCP
      port: 80             # 서비스가 노출할 포트
      targetPort: 3000     # 컨테이너(Pod)의 포트