on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          echo "version=$(date +'%Y%m%d_%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ steps.version.outputs.version }}
        run: |
          # buildx 설정
          docker buildx create --name mybuilder --use
          docker buildx inspect --bootstrap
          
          # 멀티 플랫폼 빌드 및 푸시
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t 160631388793.dkr.ecr.ap-southeast-2.amazonaws.com/sample-server:v2 \
            --push .

      - name: Deploy to EC2
        env:
            SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_KEY }}
            EC2_HOST: ${{ secrets.EC2_PUBLIC_IP }}
            EC2_USER: ec2-user
            AWS_REGION: ap-southeast-2 # 리전 정보 추가
        run: |
            ## 1. SSH 키 생성
            echo "$SSH_PRIVATE_KEY" > ssh_key.pem
            chmod 600 ssh_key.pem
            
            ## 2. SSH 접속 및 배포 (ENDSSH 앞뒤 공백 주의)
            ssh -o StrictHostKeyChecking=no -i ssh_key.pem $EC2_USER@$EC2_HOST << 'ENDSSH'
              # 원격 서버(EC2)에서 실행될 명령어들
            
              # ECR 로그인
              aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 160631388793.dkr.ecr.ap-southeast-2.amazonaws.com
            
              # 최신 이미지 Pull
              docker pull 160631388793.dkr.ecr.ap-southeast-2.amazonaws.com/sample-server:latest
            
              # 기존 컨테이너 중지 및 삭제
              docker stop sample-server || true
              docker rm sample-server || true
            
              # 새 컨테이너 실행
              docker run -d -p 3000:3000 --name sample-server 160631388793.dkr.ecr.ap-southeast-2.amazonaws.com/sample-server:latest
            ENDSSH
            
            ## 3. 임시 SSH 키 파일 제거
            rm ssh_key.pem