name: HARIN CI/CD Pipeline
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Deploy-To-EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci

      - name: Build Project
        run: npm run build

      - name: Configure AWS credentials
        env:
          AWS_SSH_KEY: ${{ secrets.AWS_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh/
          # printf를 사용하여 변수 내용을 그대로 파일에 담습니다.
          printf "%s" "$AWS_SSH_KEY" > ~/.ssh/aws.key
          chmod 600 ~/.ssh/aws.key

      - name: Deploy to EC2
        env:
          EC2_PUBLIC_IP: ${{ secrets.EC2_PUBLIC_IP }}
          EC2_USER: ec2-user
        run: |
          #Copy necessary files to EC2
          scp -o StrictHostKeyChecking=no -i ~/.ssh/aws.key -r dist package.json tsconfig.json tsconfig.build.json $EC2_USER@$EC2_PUBLIC_IP:~/sample-server
          
          #SSH into EC2 and restart the application
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/aws.key $EC2_USER@$EC2_PUBLIC_IP << 'ENDSSH'
          cd ~/sample-server
          npm install --production
          pm2 stop all || true
          pm2 start dist/main.js --name "sample-server"
          ENDSSH

      - run: echo "This job's status id ${{ job.status }}."